### ISSUE TITLE
Unable to Add Mesh to Library

### ISSUE THREAD

**Issue by DevonGrandahl** [CookieBadger/assetplacer-docs#20]
Mesh files cannot be added to the library as described in the docs. I am able to add scenes to a library, but dragging a mesh in to a library does nothing. Not sure if this is a docs issue or code issue, I'm hoping the former. 

![image](https://github.com/CookieBadger/assetplacer-docs/assets/13814170/dbef0f23-bbbc-4a0b-9d0b-21445a28648a)

(Great asset otherwise, it's been really helpful so far!)

**Comment by CookieBadger** [comment]
Hello, thanks for reporting. I see you use a .mesh file ending, that I am not familiar with. Adding meshes works with .tres or .res files, so one option would be to convert them to this format. But since that might be a lot of effort, you might first want to try if they could be handled by the plugin if you explicitly allow it, i.e. add ".mesh" to the arrays specifying which file formats are allowed in the following files:
- assetplacer/assetPalette/AssetPalette.cs at line 481:
```CSharp
string[] validEndings =
{
	".mesh", sceneFileEnding, compressedSceneFileEnding, objFileEnding, gltfFileEnding, glbFileEnding, fbxFileEnding, colladaFileEnding, blendFileEnding, resFileEnding, tresFileEnding
};
```
- assetplacer/assetPalette/previewGeneration/AssetPreviewGenerator.cs at line 144:
```CSharp
string[] validEndings =
{
	".mesh", sceneFileEnding, compressedSceneFileEnding, objFileEnding, gltfFileEnding, glbFileEnding, fbxFileEnding, colladaFileEnding, blendFileEnding, resFileEnding, tresFileEnding
};
```

Sorry for the inconvenience this causes you, and I hope this can solve your issue. I will address this in a future update.

**Comment by DevonGrandahl** [comment]
Thanks for outlining the fix! This is a very doable workaround. Turning them into scenes is also ok too, but I'm glad I can save the time.

**Comment by DevonGrandahl** [comment]
Calling this closed
